
global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: demo

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: demo-app
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]
        labels:
          service: demo-app
          env: demo
